stages:
  - build
  - test
  - format

### Build stage
#
# build the project
build:
  image: gcc:latest
  stage: build

  script:
    - echo "Build the project"
    - make

### Test stages
#
# run the unit tests
test_unit:
  image: gcc:latest
  stage: test

  dependencies:
    - build

  script:
    - echo "Run the unit tests"
    - make test-unit

# run the tests with valgrind
# to check for memory leaks
memory_leaks:
  image: gcc:latest
  stage: test

  dependencies:
    - build

  script:
    - echo "Install valgrind"
    - apt-get update -y
    - apt-get install -y valgrind
    - echo "Run the tests with valgrind"
    - make test-valgrind

# run the tests provided by our 
# professors
test_professor:
  image: gcc:latest
  stage: test

  dependencies:
    - build

  script:
    - echo "Install valgrind"
    - apt-get update -y
    - apt-get install -y valgrind
    - echo "Run professors tests"
    - make test-professor

### Format stage
#
# check the code Format
format:
  image: debian:bookworm-slim
  stage: format

  script:
    - echo "Install clang-format"
    - apt-get update -y
    - apt-get install -y clang-format
    - echo "Print clang-format version"
    - clang-format --version
    - echo "Install make"
    - apt-get install -y make
    - echo "Check the code format"
    - make check-format
