stages:
  - build
  - test
  - format

### Build stage
#
# build the project
build:
  image: gcc:latest
  stage: build

  script:
    - echo "Build the project"
    - make

### Test stages
#
# run the unit tests
test_unit:
  image: gcc:latest
  stage: test

  dependencies:
    - build

  script:
    - echo "Run the unit tests"
    - make test-unit

# run the tests with valgrind
# to check for memory leaks
memory_leaks:
  image: yag000/c_tools:latest
  stage: test

  dependencies:
    - build

  script:
    - echo "Run the tests with valgrind"
    - make test-valgrind

# runs our tests, using our professor's framework
test_tyy:
  image: yag000/c_tools:latest
  stage: test

  dependencies:
    - build

  script:
    - echo "Run tyy tests"
    - make test-tyy

# run the tests provided by our
# professors
test_professor:
  image: yag000/c_tools:latest
  stage: test

  dependencies:
    - build

  script:
    - echo "Run professors tests"
    - TEST_FOLDER_FILTER=jalon make test-professor
    - TEST_FOLDER_FILTER=rendu-final-C-bg-fg make test-professor

### Format stage
#
# check the code Format
format:
  image: yag000/c_tools:latest
  stage: format

  script:
    - echo "Check the code format"
    - make check-format
