name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: gcc:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make
