name: Format

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-format:
    runs-on: yag000/c_tools:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check format
        run: make check-format
